from __future__ import annotations

import csv
import io
from datetime import date, timedelta
from decimal import Decimal, InvalidOperation

import requests
from psycopg2.extras import execute_values

from database.connection import get_connection


START_DATE = date(2023, 1, 1)
END_DATE = date(2026, 8, 31)

TARGET_CURRENCY = "USD"

SOURCE_CURRENCIES = [
    "AUD",
    "CAD",
    "EUR",
    "GBP",
    "INR",
    "SGD",
    "USD",
]

ECB_URL = (
    "https://data-api.ecb.europa.eu/service/data/"
    "EXR/D.USD+GBP+AUD+CAD+INR+SGD.EUR.SP00.A"
)


def fetch_ecb_rates() -> dict[date, dict[str, Decimal]]:
    """
    Fetch daily ECB EUR-based reference rates.

    ECB convention:
        1 EUR = X units of source currency.

    Returns:
        {
            date: {
                "USD": Decimal(...),
                "GBP": Decimal(...),
                ...
            }
        }
    """

    response = requests.get(
        ECB_URL,
        params={
            "startPeriod": (
                START_DATE - timedelta(days=14)
            ).isoformat(),
            "endPeriod": END_DATE.isoformat(),
            "format": "csvdata",
        },
        timeout=60,
    )

    response.raise_for_status()

    rates_by_date: dict[
        date,
        dict[str, Decimal],
    ] = {}

    reader = csv.DictReader(
        io.StringIO(response.text)
    )

    for row in reader:

        observation_date = date.fromisoformat(
            row["TIME_PERIOD"]
        )

        currency = row["CURRENCY"]

        try:
            eur_based_rate = Decimal(
                row["OBS_VALUE"]
            )
        except (InvalidOperation, TypeError):
            raise ValueError(
                f"Invalid ECB rate: "
                f"{row['OBS_VALUE']}"
            )

        rates_by_date.setdefault(
            observation_date,
            {}
        )[currency] = eur_based_rate

    return rates_by_date


def build_usd_rates(
    ecb_rates: dict[date, dict[str, Decimal]],
) -> list[tuple]:
    """
    Convert ECB EUR-based rates into:

        1 source currency = X USD

    Example:

        ECB:
            1 EUR = 1.10 USD
            1 EUR = 90 INR

        Derived:
            1 INR = 1.10 / 90 USD
    """

    rows = []

    # Find the most recent ECB observation on or before
    # the first requested simulation date.
    prior_dates = [
        observation_date
        for observation_date in ecb_rates
        if observation_date <= START_DATE
    ]

    if not prior_dates:
        raise ValueError(
            "No ECB rate available on or before "
            f"{START_DATE}"
        )

    latest_available_date = max(
        prior_dates
    )

    latest_available_rates = ecb_rates[
        latest_available_date
    ]

    current_date = START_DATE

    while current_date <= END_DATE:

        if current_date in ecb_rates:

            latest_available_rates = (
                ecb_rates[current_date]
            )

        if latest_available_rates is None:
            raise ValueError(
                "No ECB rate available on or before "
                f"{current_date}"
            )

        eur_usd = latest_available_rates["USD"]

        for source_currency in SOURCE_CURRENCIES:

            if source_currency == "EUR":
                fx_rate = eur_usd

            elif source_currency == "USD":
                fx_rate = Decimal("1")

            else:

                eur_source = latest_available_rates.get(
                    source_currency
                )

                if eur_source is None:
                    raise ValueError(
                        f"Missing ECB rate for "
                        f"{source_currency} on "
                        f"{current_date}"
                    )

                fx_rate = (
                    eur_usd / eur_source
                )

            fx_rate = fx_rate.quantize(
                Decimal("0.0000000001")
            )

            rows.append(
                (
                    current_date,
                    source_currency,
                    TARGET_CURRENCY,
                    fx_rate,
                )
            )

        current_date += timedelta(days=1)

    return rows


def load_rates(rows: list[tuple]) -> None:

    connection = get_connection()

    try:

        with connection.cursor() as cursor:

            # ------------------------------------------------------
            # Clear existing rows generated by this seed script.
            # ------------------------------------------------------

            cursor.execute(
                """
                DELETE FROM fx_rates
                WHERE target_currency = %s
                  AND rate_date BETWEEN %s AND %s;
                """,
                (
                    TARGET_CURRENCY,
                    START_DATE,
                    END_DATE,
                ),
            )

            execute_values(
                cursor,
                """
                INSERT INTO fx_rates (
                    rate_date,
                    source_currency,
                    target_currency,
                    fx_rate
                )
                VALUES %s
                """,
                rows,
                page_size=5000,
            )

        connection.commit()

    except Exception:

        connection.rollback()
        raise

    finally:

        connection.close()


def validate_rates() -> None:

    connection = get_connection()

    try:

        with connection.cursor() as cursor:

            cursor.execute(
                """
                SELECT
                    COUNT(*),
                    COUNT(DISTINCT rate_date),
                    COUNT(DISTINCT source_currency)
                FROM fx_rates
                WHERE target_currency = 'USD'
                  AND rate_date BETWEEN %s AND %s;
                """,
                (
                    START_DATE,
                    END_DATE,
                ),
            )

            total_rows, date_count, currency_count = (
                cursor.fetchone()
            )

            expected_days = (
                END_DATE - START_DATE
            ).days + 1

            expected_rows = (
                expected_days
                * len(SOURCE_CURRENCIES)
            )

            if total_rows != expected_rows:
                raise AssertionError(
                    f"Expected {expected_rows:,} FX rows, "
                    f"found {total_rows:,}"
                )

            if date_count != expected_days:
                raise AssertionError(
                    f"Expected {expected_days:,} dates, "
                    f"found {date_count:,}"
                )

            if currency_count != len(
                SOURCE_CURRENCIES
            ):
                raise AssertionError(
                    "Unexpected currency count: "
                    f"{currency_count}"
                )

            cursor.execute(
                """
                SELECT COUNT(*)
                FROM fx_rates
                WHERE target_currency = 'USD'
                  AND (
                      fx_rate <= 0
                      OR source_currency IS NULL
                      OR target_currency IS NULL
                  );
                """
            )

            invalid_count = cursor.fetchone()[0]

            if invalid_count != 0:
                raise AssertionError(
                    f"Invalid FX rows found: "
                    f"{invalid_count}"
                )

            cursor.execute(
                """
                SELECT COUNT(*)
                FROM fx_rates
                WHERE source_currency = 'USD'
                  AND target_currency = 'USD'
                  AND fx_rate <> 1;
                """
            )

            usd_error_count = cursor.fetchone()[0]

            if usd_error_count != 0:
                raise AssertionError(
                    "USD → USD FX rate is not 1.0"
                )

        print(
            f"FX validation passed: "
            f"{total_rows:,} rows"
        )

    finally:

        connection.close()


def main():

    print(
        "Fetching ECB exchange-rate reference data..."
    )

    ecb_rates = fetch_ecb_rates()

    print(
        f"ECB dates received: "
        f"{len(ecb_rates):,}"
    )

    rows = build_usd_rates(
        ecb_rates
    )

    print(
        f"Rows prepared: "
        f"{len(rows):,}"
    )

    load_rates(rows)

    validate_rates()

    print(
        "FX rate population completed successfully."
    )


if __name__ == "__main__":
    main()